// RobotBuilder Version: 1.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.
package org.usfirst.frc4475.Robot4475B.commands;
import edu.wpi.first.wpilibj.command.Command;
import org.usfirst.frc4475.Robot4475B.Robot;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.tables.TableKeyNotDefinedException;
/**
 *
 */
public class  TossBall3QPower extends Command {
    private double testPowerLevel;
    private double triggerPowerPostion;
    private double triggerPowerLevel;
    
    public TossBall3QPower() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
	
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.ballToss);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }
    // Called just before this Command runs the first time
    protected void initialize() {
        //SmartDashboard.putNumber("TestPowerLevel",-.85);
        try {
         testPowerLevel = SmartDashboard.getNumber("TestPowerLevel");   
        }
        catch (TableKeyNotDefinedException e){
            testPowerLevel=-.5;
            SmartDashboard.putNumber("TestPowerLevel",testPowerLevel);       
        }        
         try {
         triggerPowerPostion = SmartDashboard.getNumber("triggerPowerPostion");   
        }
        catch (TableKeyNotDefinedException e){
            triggerPowerPostion=.62;
            SmartDashboard.putNumber("triggerPowerPostion",triggerPowerPostion);       
        }        
         try {
         triggerPowerLevel = SmartDashboard.getNumber("triggerPowerLevel");   
        }
        catch (TableKeyNotDefinedException e){
            triggerPowerLevel=-1;
            SmartDashboard.putNumber("triggerPowerLevel",triggerPowerLevel);       
        }        
                
        
        Robot.ballToss.ballTossPower(testPowerLevel);
    }
    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
       if (Robot.ballToss.getBallTossPosition()>triggerPowerPostion)
           Robot.ballToss.ballTossPower(triggerPowerLevel);
    
    }
    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return (Robot.ballToss.getBallTossPosition()>=1.25);
    }
    // Called once after isFinished returns true
    protected void end() {
        Robot.ballToss.ballTossPower(0);
    }
    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
        end();
    }
}
